### ISSUE TITLE
Stuck running services

### ISSUE THREAD

**Issue by WarningHPB** [sekai-soft/freebird#9]
Hi there, 

I'm am just going through the "I only want a Nitter instance" guide on a raspberry pi 5, I have docker installed and i am getting stuck running the command:

"docker compose -f docker-compose.nitter.yml up -d --scale nitter-auth=0" 

I keep getting the following right after running the above command 

WARN[0000] /home/warning/guide-nitter-self-hosting/docker-compose.nitter.yml: `version` is obsolete 
no such service: nitter-auth

Any ideas? sorry I am a complete noob and just wanted to use nitter to browse twitter.

**Comment by KTachibanaM** [comment]
Made some changes to this setup very recently and I forgot the update the command. You shouldn't be needing the `--scale nitter-auth=0` section now.

**Comment by KTachibanaM** [comment]
I don't think you need to change the ip address in nitter.conf. You should probably change the port mapping in `docker-compose.nitter.yml` file from `"127.0.0.1:8080:8081"` into `"0.0.0.0:8080:8081"` (I also updated the code) so that the docker container is available on your LAN. You should then be able to access it using "your pi ip:8080".
